AWSTemplateFormatVersion: "2010-09-09"
Description: Optional custom domain + ACM certificate + ALB HTTPS listener.

Parameters:
  EnvName:
    Type: String
    AllowedValues: [dev, prod]
    Default: dev
  DomainName:
    Type: String
    Default: moodoftheday.fun
  HostedZoneId:
    Type: String
    Description: Route53 hosted zone id for DomainName.
  Subdomain:
    Type: String
    Default: ""

Conditions:
  HasSubdomain: !Not [!Equals [!Ref Subdomain, ""]]

Resources:
  DomainCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !If
        - HasSubdomain
        - !Sub ${Subdomain}.${DomainName}
        - !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !If
            - HasSubdomain
            - !Sub ${Subdomain}.${DomainName}
            - !Ref DomainName
          HostedZoneId: !Ref HostedZoneId

  HttpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn:
        Fn::ImportValue:
          Fn::Sub: Mood-${EnvName}-AlbArn
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref DomainCertificate
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Fn::ImportValue:
              Fn::Sub: Mood-${EnvName}-AlbTargetGroupArn

  AppAliasRecordA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !If
        - HasSubdomain
        - !Sub ${Subdomain}.${DomainName}
        - !Ref DomainName
      Type: A
      AliasTarget:
        DNSName:
          Fn::ImportValue:
            Fn::Sub: Mood-${EnvName}-LoadBalancerDnsName
        HostedZoneId:
          Fn::ImportValue:
            Fn::Sub: Mood-${EnvName}-AlbCanonicalHostedZoneId

  AppAliasRecordAAAA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !If
        - HasSubdomain
        - !Sub ${Subdomain}.${DomainName}
        - !Ref DomainName
      Type: AAAA
      AliasTarget:
        DNSName:
          Fn::ImportValue:
            Fn::Sub: Mood-${EnvName}-LoadBalancerDnsName
        HostedZoneId:
          Fn::ImportValue:
            Fn::Sub: Mood-${EnvName}-AlbCanonicalHostedZoneId

Outputs:
  CertificateArn:
    Value: !Ref DomainCertificate
    Export:
      Name: !Sub Mood-${EnvName}-CertificateArn

  AppDomainName:
    Value: !If
      - HasSubdomain
      - !Sub ${Subdomain}.${DomainName}
      - !Ref DomainName
    Export:
      Name: !Sub Mood-${EnvName}-AppDomainName
