AWSTemplateFormatVersion: "2010-09-09"
Description: Mood app container registry.

Parameters:
  EnvName:
    Type: String
    AllowedValues: [dev, prod]
    Default: dev

Resources:
  AppRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub mood-app-${EnvName}
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only the latest 20 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 20
                },
                "action": { "type": "expire" }
              }
            ]
          }

Outputs:
  RepositoryName:
    Value: !Ref AppRepository
    Export:
      Name: !Sub Mood-${EnvName}-RepositoryName

  RepositoryUri:
    Value: !GetAtt AppRepository.RepositoryUri
    Export:
      Name: !Sub Mood-${EnvName}-RepositoryUri
